# Generated by Django 5.2.6 on 2025-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investor',
            name='holdings',
            field=models.ManyToManyField(related_name='holders', through='app.Holding', to='app.asset'),
        ),
    ]
